version: 2.1
orbs: 
  node: circleci/node@5.0.2
  npm-publisher: uraway/npm-publisher@0.2.0

installPnpm: &installPnpm
  name: Nodejs Version
  command: | 
    node --version
    npm install -g pnpm

pnpmInstall: &pnpmInstall
  name: pnpm install
  command: pnpm install --no-frozen-lockfile
    
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: *installPnpm
      - run: *pnpmInstall
      - run:
          name: pnpm build
          command: pnpm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
  test:
    executor: node/default
    steps:
      - checkout
      - run: *installPnpm
      - run: *pnpmInstall
      - run:
          name: pnpm test
          command: pnpm run test:run
  publish:
    executor: node/default
    steps:
      - attach_workspace:
          at: dist
      - npm-publisher/publish-from-package-version:
          publish-token-variable: NPM_TOKEN
        

workflows:
  publish_my_app:
    jobs:
      - test
      - build:
          requires:
            - test
      - publish:
          requires:
            - build
  
