version: 2.1
orbs: 
  node: circleci/node@5.0.2
    
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Nodejs Version
          command: | 
            node --version
            npm install -g pnpm
      - run: 
          name: pnpm install
          command: pnpm i
      - run: 
          name: pnpm build
          command: pnpm run bulid
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: pnpm i --frozen-lockfile
      - run: 
          name: pnpm Version
          command: pnpm --version
      - run:
          name: pnpm test
          command: pnpm run test:run
workflows:
  test_my_app:
    jobs:
      - build
      - test:
          requires:
            - build
  
  
