version: 2.1
orbs: 
  node: circleci/node@5.0.2
    
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: pnpm install
      - run:
          name: Nodejs Version
          command: | 
            node --version
            pnpm --version
      - run: 
          name: pnpm build
          command: pnpm run bulid
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: pnpm install
      - run:
          name: pnpm test
          command: pnpm run test:run
workflows:
  test_my_app:
    jobs:
      - node/run:
          setup:
            - run: 
                name: install -g pnpm
                command: npm install -g pnpm
      - build
      - test:
          requires:
            - build
  
  
