version: 2.1
orbs: 
  node: circleci/node@5.0.2

installPnpm: &installPnpm
  name: Nodejs Version
  command: | 
    node --version
    npm install -g pnpm

pnpmInstall: &pnpmInstall
  name: pnpm install
  command: pnpm install --no-frozen-lockfile
    
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: *installPnpm
      - run: *pnpmInstall
      - run:
          name: pnpm build
          command: pnpm run build
  test:
    executor: node/default
    steps:
      - checkout
      - run: *installPnpm
      - run: *pnpmInstall
      - run:
          name: pnpm test
          command: pnpm run test:run

workflows:
  test_my_app:
    jobs:
      - build
      - test:
          requires:
            - build
  
  
