version: 2.1
orbs: 
  node: circleci/node@5.0.2
    
docker: &docker
  docker:
      - image: 'cimg/base:stable'


jobs:
  setup:
    <<: *docker
    steps:
      - checkout
      - run:
          name: Nodejs Version
          command: node --version
      - run:
          name: install -g pnpm
          command: npm intall -g pnpm
      - run: 
          name: pnpm Version
          command: pnpm --version
      
  build:
    <<: *docker
    steps:
      - checkout
      - run: 
         name: bulid
         command: echo "this is bulid"
      - run:
          name: pnpm Version
          command: pnpm --version


workflows:
  test_my_app:
    jobs:
      - setup
      - build
  
  
